services:
  - docker
addons:
  organization: "inseefrlab"
script:
  - docker build -t juliedjidji/djangoapp:latest .
deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push juliedjidji/djangoapp:latest
  on:
    branch: master
