# Generated by Django 3.0.4 on 2020-07-30 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('label_in', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelingByHand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('label_in', models.CharField(max_length=100000)),
                ('label_out', models.TextField()),
                ('probability', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelingDone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_label', models.IntegerField(blank=True, null=True)),
                ('label_in', models.CharField(max_length=100000)),
                ('author', models.TextField(blank=True, null=True)),
                ('label_out', models.TextField(blank=True, null=True)),
                ('probability', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('unknown', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelingOnGoing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_label', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelingToDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_in', models.CharField(max_length=100000)),
                ('tableName', models.TextField(blank=True, null=True)),
                ('categ', models.TextField(blank=True, null=True)),
                ('ean', models.TextField(blank=True, null=True)),
                ('ongoing', models.PositiveIntegerField(blank=True, default=0)),
                ('labeled', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
