# Generated by Django 3.0.4 on 2020-03-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABTest',
        ),
    ]
