# Generated by Django 3.0.4 on 2020-03-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='prediction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
