# Generated by Django 3.0.4 on 2020-03-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_auto_20200331_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='label',
        ),
    ]
