# Generated by Django 3.0.4 on 2020-03-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_remove_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prediction',
            field=models.TextField(),
        ),
    ]
