# Generated by Django 3.0.4 on 2020-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0011_auto_20200428_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labellisationfromlist',
            name='encours',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labellisationfromlist',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labellisationfromlist',
            name='labellise',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labellisationfromlist',
            name='prediction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
