# Generated by Django 3.0.4 on 2020-04-28 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0012_auto_20200428_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labellisationfromlist',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
