# Generated by Django 3.0.4 on 2020-04-30 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0013_auto_20200428_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabellisationManuelle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('libelle', models.CharField(max_length=200)),
                ('label', models.TextField()),
                ('prediction', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LabellisationFromList',
        ),
        migrations.AddField(
            model_name='labellisation',
            name='encours',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labellisation',
            name='labellise',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labellisation',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='labellisation',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labellisation',
            name='prediction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
